### ISSUE TITLE
Update Element with Thread

### ISSUE THREAD

**Issue by wdog** [jwlodek/py_cui#54]
I've this little examples that does not work... It' doesn't update the screen until I press a key.

Basically what I want is to run a thread that updates some element and update the screen
Can you help me to understand why it is not completely working?  

```python
#!/usr/bin/env python3

import py_cui
import threading
import time
from datetime import datetime


class App:
    def __init__(self, master):
        self.master = master
        self.g1 = self.master.add_scroll_menu('PANEL',
                                              0, 0, row_span=6, column_span=6)
        thread = threading.Thread(target=self.thread_update, args=())
        thread.daemon = True
        thread.start()

    def thread_update(self):
        try:
            while True:
                d = "TIME:{}".format(datetime.now().strftime('%X'))
                self.g1.add_item(d)
                time.sleep(1)
        except Exception as e:
            print(e)


root = py_cui.PyCUI(9,6)
root.toggle_unicode_borders()
root.set_title('Test')
s = App(root)
root.start()
```

Is it a thread/curses limitation?

**Comment by jwlodek** [comment]
It is a `curses` limitation. The 'wait for event' call in the main draw loop is blocking, so the screen is only refreshed when a key is pressed. You can work around this by setting the `_loading` attribute to `True` in your thread, and that will continuously run the draw loop without waiting for input, but then until you set `_loading` back to false you will not be able to enter keys.

I originally had put the draw loop on a separate thread so that you could do screen updates without key presses, but the refresh speed was too slow and it wasn't really practical.

**Comment by wdog** [comment]
I've found a "dirty" workaround simulating a keypress

this is for someone who really need to use threads 'easily' not properly

install package

```
pip install pyinput
````

import class

```python
from pynput.keyboard import Key, Controller
```

add the following

```python
# __init__
self.keyboard = Controller()
```


```python
# in thread function
self.keyboard.press('a')
self.keyboard.release('a')
```

I've to read the pyinput code to find a better solution here

**Comment by wdog** [comment]
Adding to the thread function

```python
self._stdscr.timeout(1000)
```

seems to work. @jwlodek what do you think it is correct? 


> **window.timeout(delay)**
> Set blocking or non-blocking read behavior for the window. If delay is negative, blocking read is used (which will wait indefinitely for input). If delay is zero, then non-blocking read is used, and getch() will return -1 if no input is waiting. If delay is positive, then getch() will block for delay milliseconds, and return -1 if there is still no input at the end of that time.

**Comment by jwlodek** [comment]
That may work... I'll have to make sure it doesn't break compatibility anywhere though.

**Comment by jreneew2** [comment]
When ssh'ed into a terminal and updating elements from another thread using the workaround above, the screen will slightly flicker at the rate of the timeout. Not sure how to fix, and a longtimeout value is unacceptable in our usecase.

**Comment by jwlodek** [comment]
The flicker is caused by curses not being able to render the entire screen fast enough. The reason for this is that `py_cui` uses immediate mode rendering, or in other words it builds the entire frame in memory and then tells the renderer to draw it, meaning all screen elements are drawn during every refresh. This is why I didn't initially add support for a constant refresh, and made the screen update only on events, to minimize flicker (aside from loading popups). 

The solution would be to allow for the library to only re-draw portions of the screen that change between frames, which should help the refresh speed be faster. I have thought of how I might do this and even put together some boilerplate code, but overall this would be a much more complicated feature to develop than the free time I have currently allows for, so it has been put on the back burner.

**Comment by jreneew2** [comment]
Ah ok. The issue seems to only be over ssh so we can deal with that! Thanks for the quick response!

**Comment by jwlodek** [comment]
I have pushed changes to the `v0.1.2` branch that should improve performance and reduce flicker. I've tested on some weak machines and over ssh and I no longer see the flickering at the very least. If you have the chance, could you test it on your end to see if it fixed your issue? @jreneew2

**Comment by jreneew2** [comment]
seems to be fixed to me! thanks so much

**Comment by jwlodek** [comment]
Great! The new version will be uploaded on PyPi in the next few weeks with the fixes.

**Comment by zocker-160** [comment]
I just ran into this exact issue, but sadly it still does not work using the latest version with the exact example above.

I think this issue should get reopened @jwlodek.

**Comment by zocker-160** [comment]
ok using `set_refresh_timeout(1)` solved the issue for me.

**Comment by jwlodek** [comment]
Yes, by default it still uses the original draw call blocking approach to not break compatibility, since I wrote a bunch of programs that relied on that. If you would like to use parallel threads you need to set the refresh timeout, so then the library knows to redraw the UI periodically to see any changes made in a different thread.

**Comment by zocker-160** [comment]
yep I got it working now, maybe this function should get better documented by adding this exact example to the [examples page](https://jwlodek.github.io/py_cui-docs/examples/) on the wiki

**Comment by jwlodek** [comment]
Yeah, for sure some of the documentation (like for this) needs to be overhauled eventually, I've just been busy with work lately, hopefully I have some extra free time in the coming months to dedicate to this.
